version: '3.7'

services:
  migration:
    build:
      context: .
      dockerfile: .docker/Dockerfile-migration
    env_file:
      - .env
    volumes:
      - .:/opt/migration
    links:
      - postgres
    depends_on:
      - postgres
    networks:
        - reactphp-simple-orm

  postgres:
    ports:
      - 5432:5432
    image: postgres:11.22-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
        - reactphp-simple-orm

networks:
    reactphp-simple-orm:
        name: reactphp-simple-orm
